runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.php

- url: /dbh.inc.php
  script: /includes/dbh.inc.php

- url: /login.inc.php
  script: /includes/login.inc.php

- url: /logout.inc.php
  script: /includes/logout.inc.php

- url: /(.+\.php)$
  script: \1

- url: /style
  static_dir: style.css
